// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmqwicfnxahvihwhtsao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcXdpY2ZueGFodmlod2h0c2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNjkyMTksImV4cCI6MjA4OTY0NTIxOX0.LScPie8eeawDzNWyDMbQXkkt8hFzHvUGRSFjgU09g9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});